language: python
sudo: false
env:
  global:
    - secure: "3p23U7qqhUbE1EJ6yIDSa6cwOXslduQi6Y31QhQj6QsLc+b8oal8UjhLgPenIfWGT5pkJ15cppUU1OePVKx1lZr8rfFg+RLo6AYWUnoaYffYdwtK+4eaf0Xk25TSc/NyIA3n3rFoFS0wgQ5PWlA0W2RHtoPh0trkAD1+de2k6C6kBoWJUBCcQLNCVZSeqPe86apSLVuK9N/5E6gYaTbtyoejso2e6zjEviGGfJxwrBSVvTzgJulDiYqZ/7sP7oURBZOAfAZnGpxc+YRQv1tIK0M7SYFf0am3WlhzhJHwYcReRlwfdbeQ/VvZXR09AV2InIfelSo0OnQDosg+AQevrOcJvDWBRfzr470RORwPUTY9xu+OFFQOx90F49exzTFmGZGAUVIT515JsCUb8PKH4Nz1HRtopUwII65exSVlJTxP7TDu03XV/MyA5aDJfcWtOmPsME+nKpvNrd/TmrxquY8KvEH1hrEJBOg742dIIUTbObJkiCSDsLtQS9tg0vJA9H3uqjN8a6zm7Nt9VQ5Ji0GiHkM6RrBXrvC9+GbK1uCtrdmhCuKWVSe13AVoaD3qdYVFfT6y2xEy3CUiXZCNIfxIY1dNa+QLPwYWZvQheMo5JxzGkuD/Mak7CFY6Bqm9J2XR0d1wvYdrvf4njBlw/YHThR8lPD8cemY9mGGA27k="
  matrix:
    - PRECEDENCE='default'
    - PRECEDENCE='default bleeding'

matrix:
  allow_failures:
    - env: PRECEDENCE='default'

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/matplotlib

services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/mc
  - export PATH=~/mc/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no --set quiet true
  - conda config --append channels nsls2forge
  - conda config --append channels anaconda
  - conda config --append channels conda-forge
  - conda update conda --yes
  - export CONDARC=ci/condarc
  - export MDS_HOST=localhost
  - export MDS_DATABASE=test
  - export MDS_TIMEZONE=US/Eastern
  - mkdir -p /home/travis/.config/metadatastore
  - 'echo ''port: 27017'' > /home/travis/.config/metadatastore/connection.yml'
  - export FS_HOST=localhost
  - export FS_DATABASE=test
  - mkdir -p /home/travis/.config/filestore
  - 'echo ''port: 27017'' > /home/travis/.config/filestore/connection.yml'

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create -n testenv --file requirements/build.txt --file requirements/run.txt --file requirements/test.txt --file requirements/docs.txt

script:
  - set -e
  - source activate testenv
  - coverage run run_tests.py
  - coverage report -m
  - codecov
  # - flake8 xpdan
  - cd docs
  - make html
  - cd ..
  - doctr deploy . --built-docs ./docs/_build/html;
